### ISSUE TITLE
Error Loading Packages in Individual Location Tracking

### ISSUE THREAD

**Issue by JEM54** [DeniseCaiLab/ezTrack#14]
Hi,

When I run Step 1 of the Location Tracking Individual Module, I receive the following error:

![Import Error](https://user-images.githubusercontent.com/62354988/77000630-1383b700-692f-11ea-9fdb-9e4b51e2e454.PNG)

If relevant, the ezTrack conda environment I installed is as follows: 
conda create -y -n ezTrack -c conda-forge python=3.6 pandas=0.23.0 matplotlib=3.1.1 opencv=3.4.3 jupyter=1.0.0 holoviews=1.12.3 scipy=1.2.1

I'm brand new to Python (and programming as a whole) and am unsure how to proceed - any advice would be greatly appreciated.

Thank you so much!

**Comment by ZachPenn** [comment]
Glad you're checking out ezTrack as newbie to Python.  That's great!  

It seems that all of the packages might not be present.  Did you make sure to activate the environment before opening jupyter lab?  If so, you should see the ezTrack environment name where it is in the image below.  If you don't see 'ezTrack' there, the reason you're getting the error is because you haven't activated the ezTrack environment, which must be done before each time you open jupyter notebook to run ezTrack.

![image](https://user-images.githubusercontent.com/38541976/77011288-e7256600-6941-11ea-8794-099d196ead6e.png)

If the ezTrack environment was activated before opening jupyter notebook and getting this error, could you please do the following:
1) From your terminal/ananconda console, activate the ezTrack environment
2) Enter the command `conda list`
This will give a list of packages installed in the environment and will help me figure out exactly why you're getting this error.  In particular, I want to make sure that bokeh and holoviews are installed.  

Thanks.
-Zach

**Comment by JEM54** [comment]
Zach,
Thanks for the quick response! I did have the environment activated, so all good on that. Here is the list of packages: 

![image](https://user-images.githubusercontent.com/62354988/77076061-aa9d4d00-69c9-11ea-8daa-6273d1aa61f4.png)
![image](https://user-images.githubusercontent.com/62354988/77076145-c9034880-69c9-11ea-93a9-14b1ec8e8d43.png)

**Comment by ZachPenn** [comment]
I think I have the issue sorted out.  A newer version of bokeh came out that wasn't compatible with the version of the holoviews package used; I hadn't originally specified the bokeh version during install but clearly I should have.  

I have updated the install instructions on the README page but you can do the following from your console to just update the bokeh version in your ezTrack environment:
```
conda activate ezTrack
conda install bokeh=1.2.0
```
If for some reason the above code doesn't work you might do a clean install.  To remove the ezTrack environment you have and then reinstall enter the following commands:
```
conda env remove -n ezTrack
conda create -y -n ezTrack -c conda-forge python=3.6 pandas=0.23.0 matplotlib=3.1.1 opencv=3.4.3 jupyter=1.0.0 holoviews=1.12.3 scipy=1.2.1 bokeh=1.2.0
```

Please let me know if this solves the issue for you.
Best,
Zach

**Comment by ZachPenn** [comment]
Also, go ahead and re-download the LocationTracking_Functions.py file.  There was a small bug from a new feature I added last week that has now been fixed.  I figured I'd tell you before you run into it.
