### ISSUE TITLE
Be able to save motion trace?

### ISSUE THREAD

**Issue by keeleereid** [DeniseCaiLab/ezTrack#2]
I really love the program, it has made analyze data in my lab super easy. However, I would love it even more if there was the option to save the motion trace that the program outputs. Also to improve on that further a heat map or something like that for where the animal was the most would be really cool.

**Comment by ZachPenn** [comment]
You are able to save the motion trace! There is a save button at the top of each figure, which will save the figure as a png.

We hadn't implemented heatmaps in part because the trace of where the animal is seemed to be more informative.  However, a couple of people have requested this and it will likely be an option in the next release.  

Alternatively,
1.  Check out the holoviews documentation for creating heatmaps (http://holoviews.org/reference/elements/bokeh/HeatMap.html#bokeh-gallery-heatmap).  You could create a heatmap of the x/y location of your animal and superimpose on the reference image.  

2. You can also try to reduce the alpha in `points = hv.Scatter(np.array([location['X'],location['Y']]).T).opts(color='red',alpha=.8,size=3)`.  This sets the transparency of each dot in the trace of where the animal is.  With lower alpha the animal will need to return to location multiple times for the trace to be clearly visibly.  Maybe combine this with a higher `size` as well.

**Comment by DeniseCaiLab** [comment]
The development branch (`dev`) now includes heatmaps with both individual and batch processing in the location tracking module (https://github.com/DeniseCaiLab/ezTrack/branches).  This will be added to the second release of ezTrack, coming shortly.
