### ISSUE TITLE
Issue with latest update (fixed 8b, now problem with 8c)

### ISSUE THREAD

**Issue by ewo478** [DeniseCaiLab/ezTrack#25]
Hi,
I'm getting an error: "TypeError: Locate() missing 1 required positional argument: 'video_dict'" in cell 8b, screenshot attached
![Screenshot 2021-04-13 081645](https://user-images.githubusercontent.com/82358639/114456190-aecd8580-9c30-11eb-8b52-cf8737ba66d1.png)

**Comment by ewo478** [comment]
I saw there was updated files available for this, downloaded those now have a syntax error in 2.

![Screenshot 2021-04-13 082924](https://user-images.githubusercontent.com/82358639/114457648-5f885480-9c32-11eb-815f-971bf38c6c14.png)

**Comment by ewo478** [comment]
Fixed with comma but now have issue with 8c processing only 5% of frames before stopping
![Screenshot 2021-04-13 090007](https://user-images.githubusercontent.com/82358639/114462145-c60f7180-9c36-11eb-8fcf-ede6663a9e59.png)

**Comment by ewo478** [comment]
Similarly to issue 18 raised by cadeichsel, tried MP4 instead of avi. This generated the csv.

There was a massive drop in f/s (80 to 25) and total frames to analyze (~45000 to ~15500). Is this the reason? Is there a recommendation for f/s or total frames?

Had dsmpl = 0.5 in step 2 for both mp4 and avi.

**Comment by ZachPenn** [comment]
ezTrack will process every readable frame in your video.  The denominator in the process bar is based upon metadata in your video codec, and not the actual number of readable frames in the video.  Same deal with frame rate; it's metadata, and can be misleading.  I've seen a few instances of videos with a large amount of empty/corrupt frames.  I'm guessing your issue has something to do with your videos rather than ezTrack.

If you want to confirm that this isn't specific to ezTrack, you could play the video in VLC, which will show the number of decoded frames under video information as you play the video

**Comment by ewo478** [comment]
Is this the information from VLC you mean? 
![Screenshot 2021-04-13 141850](https://user-images.githubusercontent.com/82358639/114487383-9d51a100-9c63-11eb-9dbf-a14e34f4314d.png)

**Comment by ZachPenn** [comment]
Yes.  The total number of frames doesn't seem to be 45,000 either though, but maybe that's because you didn't play the whole thing.

**Comment by ewo478** [comment]
I reran the .avi through the notebook and in VLC from start to finish, still saw the same discrepancy in the frame number and 0 lost frames, so I'm not sure why this is happening.  Converting to mp4 works so I will go with this, thanks for your help and for developing this software
