### ISSUE TITLE
Frames calculated by ezTrack

### ISSUE THREAD

**Issue by h1408** [denisecailab/ezTrack#27]
Hello, I've been trying to run behavioral videos on ezTrack and have been using the frame rate to calculate the start/end frames. One thing I've noticed is that when I set the end frame to None and then run step 3, the total frames calculated is much higher than what I'm seeing it is by getting the total frames of the video in Matlab. Also the 'nominal fps' is different from the frame rate I see on my computer of the video. What would this difference mean in terms of analyzing the video? If I put an end frame of 15000 but ezTrack is calculated the total frames to be 600,000+ would this mean it's not actually analyzing the full video? I would appreciate any insight you have on this, thank you!

**Comment by ZachPenn** [comment]
Could you please provide more information on the filetype being used?  The nominal fps is taken directly from the video codec metadata so I'm not sure why there would be a discrepancy.  As to the number of frames, some video file types seem to have a large number of irretrievable or blank frames, and ezTrack simply reports the total, including these 'blank' frames.  If the blank frames are at the end of the video, after all the frames you actually want to process, there's no issue.  However, if they are intermixed, you will likely encounter issues.

I might try converting to another filetype.

**Comment by h1408** [comment]
Hello, this is a .wmv filetype. When I open it on a windows pc, the frame rate shows as 25 frames/second. In addition, I have run the video file through MATLAB to assess the properties of the file and it also shows it as 25 frames/second, along with a total number of frames as 16000 as in the attached photo. However, in ezTrack the frames per second is shown as 1000 and the total number of frames is over 600000 (photo of this is also attached). I thought there weren't any blank frames since I was able to find the total number of frames of the video which is around 16000. 
Would converting potentially lead to loss of information?
Thanks so much!
![Screenshot (4)](https://user-images.githubusercontent.com/80368001/117736998-bc354b80-b1ad-11eb-9ab9-7a5719fda7f7.png)

![Screenshot (3)](https://user-images.githubusercontent.com/80368001/117737073-ea1a9000-b1ad-11eb-9d20-3199933a5b6c.png)

![Screen Shot 2021-05-10 at 4 30 23 PM](https://user-images.githubusercontent.com/80368001/117736901-9740d880-b1ad-11eb-8815-dc44d818972f.png)

**Comment by ZachPenn** [comment]
Looking more into the frame issue, I don't think it's so much that you are missing frames, but that you have incomplete frames.  This is a typical of many video compression algorithms to support support smaller file sizes (see https://en.wikipedia.org/wiki/Video_compression_picture_types for a description of 'p frames').  Unfortunately, ezTrack does not currently possess a good way to handle videos with these incomplete, 'p frames', and simply skips them.  While all full frames can be processed, frame indexing gets really weird (because key frames 1,2,3,4,5 might have indices 1,11,21,31,41, or something like this).

It may be possible for me to implement something to handle this, but I don't have any videos like yours so I can't do any testing.  If you would like to post a video here or reach out to me via email, please do.  I would like to start dealing with this.  

With respect to the frame rate issue, I really am not sure why ezTrack isn't read the metadata properly.  Again, if you'd be willing to post an actual video, it'd be great to check it out.

**Comment by h1408** [comment]
Hi Zach,

Thank you so much for your reply and help with this! I can definitely share some videos with you via email! Where should I send them to?





________________________________

**Comment by ZachPenn** [comment]
You can reach out to me at zachpen87@gmail.com

**Comment by ZachPenn** [comment]
I have implemented fixes to help test for these issues (`commit 0fec6e4`), and have updated instructions to specify that ezTrack should not be used with temporal compression algorithms.  I am closing this issue for now.
