### ISSUE TITLE
Failure to Load Necessary Packages

### ISSUE THREAD

**Issue by matinsaba** [DeniseCaiLab/ezTrack#54]
Hi, 

When I am tried to load necessary packages I got the error below: 

cannot import name 'Markup' from 'jinja2' (/Users/user/opt/miniconda3/envs/ezTrack/lib/python3.8/site-packages/jinja2/__init__.py)

**Comment by ZachPenn** [comment]
This is a compatibility issue with the latest version of jinja2. 

Try the following:

From Terminal, activate your environment (`conda activate ezTrack`), and then enter the following command:
```
conda install jinja2=3.0.3
```

After you should be able to open jupyter and run things without issue.

**Comment by matinsaba** [comment]
Hi, 
Thank you for your help. that was one of attempt to fix it and now I am seeing another error. 
module 'typing' has no attribute '_SpecialForm'

I did uninstall and install the conda, deleted the ezTrack from my .env folder and install it again. 

I also did try to run the program on another computer in the lab and still got the same error.

**Comment by ZachPenn** [comment]
This is good to know.  Two things that could help me resolve this:
- What operating system are you using?
- Could you provide me with the full package list?  After activating your ezTrack environment in the terminal input the command `conda list`.

**Comment by ZachPenn** [comment]
A few other things:
- What web browser are using? I ask because I've had the best performance with Google Chrome.
- Have you updated to the latest conda version? `conda update conda`
- Did you add `jinja2=3.03 to the ezTrack environment install command or did you first install ezTrack and then install that jinja2 version? I suggested doing it the latter way so you wouldn't have to uninstall ezTrack but I've had some issues updating packages in this sort of successive way.

Running on a macbook with Google Chrome, after using the following install command, I am unable to replicate your error:
```
conda create -y -n ezTrack -c conda-forge python=3.8 pandas=1.3.2 matplotlib=3.1.1 opencv=4.5.3 jupyter=1.0.0 holoviews=1.14.5 scipy=1.7.1 scikit-learn=0.24.2 bokeh=2.3.3 jinja2=3.0.3 tqdm
```

Another thing, before doing this please be sure to do a clean environment removal:
```
conda remove --name ezTrack --all
```

Let me know how it goes.
