### ISSUE TITLE
Module not found errors

### ISSUE THREAD

**Issue by ojgannon** [DeniseCaiLab/ezTrack#80]
Hi, 

I'm very new to python (and coding in general) and I am trying to analyze behavior data using ezTrack. I downloaded miniconda and opened ezTrack in the jupyter notebook. When I run the first cell, I get the error shown below:
![image](https://github.com/denisecailab/ezTrack/assets/143829071/51c5cc52-0094-41f3-9be1-939ccd946179)

Could the issue be related to the packages that I have installed? 
![image](https://github.com/denisecailab/ezTrack/assets/143829071/dcf18f41-6450-4677-b99c-057531cc9f20)
![image](https://github.com/denisecailab/ezTrack/assets/143829071/1149cc4e-6ee8-4f31-b765-754414bff064)

Any help would be very much appreciated! Thank you so much!
Olivia

**Comment by ZachPenn** [comment]
Hi Olivia,
Yes, it seems most likely this is a package issue (I'm not seeing tqdm, which is required).  I would follow the most up to date install instructions here: https://github.com/denisecailab/ezTrack/wiki/Installation.  Things have changed slightly since the initial publication.  You should uninstall before doing this (instructions at bottom of webpage provided).  
Best,
Zach

**Comment by treetrunkz** [comment]
As you can see the missing package is located in 'import LocationTrackingFunctions as lt' this could be a number of things. But you need to locate tqdm, if it's missing add it. I'd if it's not then remove it and reinstall.  

Also, there in your environment, the package doesnt exist. You may need to update your environment as well. You can use pipreqs to automatically generate a requirements.txt file based on the imports statement in any .py file or project - then download from there. Or even chain these with one command. :^)
